export const defaultCategories = [
    {
        name: 'מזון',
        type: 'expense',
        subcategories: ['סופרמרקט', 'מסעדות', 'משלוחים', 'אחר'],
        icon: '🍔',
        color: '#ff6b6b',
        isDefault: true,
    },
    {
        name: 'תחבורה ציבורית',
        type: 'expense',
        subcategories: ['אוטובוס', 'רכבת', 'מונית', 'שארמון', 'אחר'],
        icon: '🚌',
        color: '#4ecdc4',
        isDefault: true,
    },
    {
        name: 'בילויים',
        type: 'expense',
        subcategories: ['קולנוע', 'בידור', 'ספורט', 'תחביבים', 'אחר'],
        icon: '🎮',
        color: '#95e1d3',
        isDefault: true,
    },
    {
        name: 'חשבונות',
        type: 'expense',
        subcategories: ['חשמל', 'מים', 'גז', 'אינטרנט', 'טלפון', 'ארנונה', 'אחר'],
        icon: '📄',
        color: '#f38181',
        isDefault: true,
    },
    {
        name: 'שירותים דיגיטליים',
        type: 'expense',
        subcategories: ['נטפליקס', 'ספוטיפיי', 'אפל מיוזיק', 'יוטיוב פרמיום', 'אמזון פריים', 'דיסני+', 'הולו', 'אחר'],
        icon: '📱',
        color: '#6c5ce7',
        isDefault: true,
    },
    {
        name: 'כושר ובריאות',
        type: 'expense',
        subcategories: ['חדר כושר', 'יוגה', 'פילאטיס', 'בריכה', 'פיזיותרפיה', 'מאמן אישי', 'אחר'],
        icon: '💪',
        color: '#00b894',
        isDefault: true,
    },
    {
        name: 'ביטוחים',
        type: 'expense',
        subcategories: ['ביטוח רכב', 'ביטוח דירה', 'ביטוח חיים', 'ביטוח בריאות פרטי', 'ביטוח נסיעות', 'אחר'],
        icon: '🛡️',
        color: '#0984e3',
        isDefault: true,
    },
    {
        name: 'חינוך ופיתוח',
        type: 'expense',
        subcategories: ['שכר לימוד', 'ספרים', 'קורסים אונליין', 'השתלמויות', 'שפה', 'אחר'],
        icon: '📚',
        color: '#fcbad3',
        isDefault: true,
    },
    {
        name: 'מנויים ומינויים',
        type: 'expense',
        subcategories: ['עיתונים', 'מגזינים', 'קלובים', 'חברות', 'אפליקציות', 'אחר'],
        icon: '📰',
        color: '#fd79a8',
        isDefault: true,
    },
    {
        name: 'בריאות',
        type: 'expense',
        subcategories: ['רופא', 'תרופות', 'ביטוח בריאות', 'כושר', 'אחר'],
        icon: '🏥',
        color: '#aa96da',
        isDefault: true,
    },
    {
        name: 'חינוך ופיתוח',
        type: 'expense',
        subcategories: ['שכר לימוד', 'ספרים', 'קורסים אונליין', 'השתלמויות', 'שפה', 'אחר'],
        icon: '📚',
        color: '#fcbad3',
        isDefault: true,
    },
    {
        name: 'קניות',
        type: 'expense',
        subcategories: ['ביגוד', 'נעליים', 'אלקטרוניקה', 'רהיטים', 'אחר'],
        icon: '🛍️',
        color: '#ffffd2',
        isDefault: true,
    },
    {
        name: 'מגורים',
        type: 'expense',
        subcategories: ['משכנתא', 'שכירות', 'ועד בית', 'תיקונים', 'ביטוח דירה', 'אחר'],
        icon: '🏠',
        color: '#ffd93d',
        isDefault: true,
    },
    {
        name: 'תחזוקת בית',
        type: 'expense',
        subcategories: ['ניקיון', 'גינון', 'שיפוצים', 'תיקונים', 'אביזרים', 'אחר'],
        icon: '🔧',
        color: '#f39c12',
        isDefault: true,
    },
    {
        name: 'חיות מחמד',
        type: 'expense',
        subcategories: ['מזון', 'וטרינר', 'תרופות', 'צעצועים', 'טיפוח', 'אחר'],
        icon: '🐕',
        color: '#e67e22',
        isDefault: true,
    },
    {
        name: 'מתנות',
        type: 'expense',
        subcategories: ['ימי הולדת', 'חגים', 'אירועים', 'תרומות', 'אחר'],
        icon: '🎁',
        color: '#ff6bcb',
        isDefault: true,
    },
    {
        name: 'הוצאות חד פעמיות',
        type: 'expense',
        subcategories: ['ציוד', 'שיפוצים', 'נסיעות', 'רכישות גדולות', 'אחר'],
        icon: '💎',
        color: '#b19cd9',
        isDefault: true,
    },
    {
        name: 'ילדים',
        type: 'expense',
        subcategories: ['חיתולים', 'מזון תינוקות', 'צעצועים', 'ביגוד ילדים', 'חוגים', 'אחר'],
        icon: '👶',
        color: '#ff7675',
        isDefault: true,
    },
    {
        name: 'רכב ותחבורה',
        type: 'expense',
        subcategories: ['דלק', 'חניה', 'תחזוקה', 'ביטוח רכב', 'רישיון', 'אחר'],
        icon: '🚗',
        color: '#74b9ff',
        isDefault: true,
    },
    {
        name: 'חסכונות',
        type: 'expense',
        subcategories: ['הפקדה חודשית', 'פנסיה', 'קרן השתלמות', 'אחר'],
        icon: '💰',
        color: '#9b59b6',
        isDefault: true,
    },
    {
        name: 'החזרי הלוואות',
        type: 'expense',
        subcategories: ['החזר חודשי', 'הלוואה משכנתא', 'הלוואה מהבנק', 'אחר'],
        icon: '📝',
        color: '#e74c3c',
        isDefault: true,
    },
    {
        name: 'אחר',
        type: 'expense',
        subcategories: ['שונות'],
        icon: '📦',
        color: '#a8d8ea',
        isDefault: true,
    },
    {
        name: 'משכורת',
        type: 'income',
        subcategories: ['משכורת ראשית', 'משכורת נוספת', 'בונוס', 'שעות נוספות'],
        icon: '💰',
        color: '#4caf50',
        isDefault: true,
    },
    {
        name: 'השקעות',
        type: 'income',
        subcategories: ['דיבידנדים', 'ריבית', 'רווחי הון', 'קריפטו'],
        icon: '📈',
        color: '#8bc34a',
        isDefault: true,
    },
    {
        name: 'הכנסה אחרת',
        type: 'income',
        subcategories: ['מתנות', 'החזרי מס', 'פרילנס', 'שונות'],
        icon: '💵',
        color: '#66bb6a',
        isDefault: true,
    },
];

