export const defaultCategories = [
    {
        name: 'מזון',
        type: 'expense',
        subcategories: ['סופרמרקט', 'מסעדות', 'משלוחים', 'אחר'],
        icon: '🍔',
        color: '#ff6b6b',
        isDefault: true,
    },
    {
        name: 'תחבורה',
        type: 'expense',
        subcategories: ['דלק', 'תחבורה ציבורית', 'חניה', 'תחזוקת רכב', 'אחר'],
        icon: '🚗',
        color: '#4ecdc4',
        isDefault: true,
    },
    {
        name: 'בילויים',
        type: 'expense',
        subcategories: ['קולנוע', 'בידור', 'ספורט', 'תחביבים', 'אחר'],
        icon: '🎮',
        color: '#95e1d3',
        isDefault: true,
    },
    {
        name: 'חשבונות',
        type: 'expense',
        subcategories: ['חשמל', 'מים', 'גז', 'אינטרנט', 'טלפון', 'ארנונה', 'אחר'],
        icon: '📄',
        color: '#f38181',
        isDefault: true,
    },
    {
        name: 'בריאות',
        type: 'expense',
        subcategories: ['רופא', 'תרופות', 'ביטוח בריאות', 'כושר', 'אחר'],
        icon: '🏥',
        color: '#aa96da',
        isDefault: true,
    },
    {
        name: 'חינוך',
        type: 'expense',
        subcategories: ['שכר לימוד', 'ספרים', 'קורסים', 'אחר'],
        icon: '📚',
        color: '#fcbad3',
        isDefault: true,
    },
    {
        name: 'קניות',
        type: 'expense',
        subcategories: ['ביגוד', 'נעליים', 'אלקטרוניקה', 'רהיטים', 'אחר'],
        icon: '🛍️',
        color: '#ffffd2',
        isDefault: true,
    },
    {
        name: 'מגורים',
        type: 'expense',
        subcategories: ['משכנתא', 'שכירות', 'ועד בית', 'תיקונים', 'ביטוח דירה', 'אחר'],
        icon: '🏠',
        color: '#ffd93d',
        isDefault: true,
    },
    {
        name: 'מתנות',
        type: 'expense',
        subcategories: ['ימי הולדת', 'חגים', 'אירועים', 'תרומות', 'אחר'],
        icon: '🎁',
        color: '#ff6bcb',
        isDefault: true,
    },
    {
        name: 'הוצאות חד פעמיות',
        type: 'expense',
        subcategories: ['ציוד', 'שיפוצים', 'נסיעות', 'רכישות גדולות', 'אחר'],
        icon: '💎',
        color: '#b19cd9',
        isDefault: true,
    },
    {
        name: 'אחר',
        type: 'expense',
        subcategories: ['שונות'],
        icon: '📦',
        color: '#a8d8ea',
        isDefault: true,
    },
    {
        name: 'משכורת',
        type: 'income',
        subcategories: ['משכורת ראשית', 'משכורת נוספת', 'בונוס', 'שעות נוספות'],
        icon: '💰',
        color: '#4caf50',
        isDefault: true,
    },
    {
        name: 'השקעות',
        type: 'income',
        subcategories: ['דיבידנדים', 'ריבית', 'רווחי הון', 'קריפטו'],
        icon: '📈',
        color: '#8bc34a',
        isDefault: true,
    },
    {
        name: 'הכנסה אחרת',
        type: 'income',
        subcategories: ['מתנות', 'החזרי מס', 'פרילנס', 'שונות'],
        icon: '💵',
        color: '#66bb6a',
        isDefault: true,
    },
];

